"""Generate specialized editors from shared repair and account preparation sources."""
import json
from pathlib import Path
from tools.generate.task_protocol import unique_members



def generate(root: Path, check=False):
    source = root / "adapters/config-editor"
    registry = json.loads((source / "editors.json").read_text(encoding="utf-8"), object_pairs_hook=unique_members)
    if not isinstance(registry, dict) or set(registry) != {"schemaVersion", "repair", "editors"} or registry["schemaVersion"] != 1:
        raise ValueError("Invalid editor registry")
    manifests = sorted((root / "plugins/specialized").glob("*/plugin.json"))
    artifacts = {json.loads(file.read_text(encoding="utf-8"))["artifactName"] for file in manifests}
    if not isinstance(registry["editors"], dict) or set(registry["editors"]) != artifacts:
        raise ValueError("Editor registry differs from current specialized inventory")
    def module(relative, *, optional=False):
        if relative is None and optional:
            return ""
        if not isinstance(relative, str) or not relative or "\\" in relative:
            raise ValueError("Invalid editor module path")
        path = source / relative
        if path.is_symlink() or not path.resolve().is_relative_to(source.resolve()) or path.suffix != ".js":
            raise ValueError("Unsafe editor module path")
        return path.read_text(encoding="utf-8")
    repair = module(registry["repair"])
    failures = []
    count = 0
    for manifest in manifests:
        data = json.loads(manifest.read_text(encoding='utf-8'))
        if not data.get('taskProtocol', {}).get('repairRules'):
            raise ValueError('Missing repair declarations: ' + data['artifactName'])
        declaration = registry["editors"][data["artifactName"]]
        if not isinstance(declaration, dict) or set(declaration) != {"preparation", "commit"}:
            raise ValueError("Invalid editor declaration: " + data["artifactName"])
        preparation = module(declaration["preparation"], optional=True)
        commit = module(declaration["commit"], optional=True)
        content = '// Generated by tools/repo.py generate editors. Edit adapters/config-editor sources.\n'
        content += "'use strict';\n"
        content += "if (nexus.input.trigger === 'config-repair') {\n"
        content += repair
        content += '\nnexus.proposeRepair(proposeRepair(nexus.input));\n} else if (nexus.input.trigger === "config-edit-commit") {\n'
        content += commit
        content += '\n} else {\n'
        content += preparation
        content += '\n}\n'
        target = manifest.parent / 'data/editor.js'
        if data.get('configEditor') != 'data/editor.js':
            raise ValueError('Editor must be declared: ' + data['artifactName'])
        if check:
            if not target.exists() or target.read_text(encoding='utf-8') != content:
                failures.append(data['artifactName'])
        else:
            target.write_text(content, encoding='utf-8', newline='\n')
        count += 1
    if failures:
        raise ValueError('Generated editors differ: ' + ', '.join(failures))
    print(('Checked' if check else 'Generated') + f' {count} configuration editors')
