"""Generate specialized editors from shared repair and account preparation sources."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / 'tools/config-editor'


def generate(check=False):
    failures = []
    count = 0
    for manifest in sorted((ROOT / 'plugins/specialized').glob('*/plugin.json')):
        data = json.loads(manifest.read_text(encoding='utf-8'))
        if not data.get('taskProtocol', {}).get('repairRules'):
            raise ValueError('Missing repair declarations: ' + data['artifactName'])
        preparation = SOURCE / (data['artifactName'] + '.js')
        content = '// Generated by tools/generate_config_editors.py. Edit tools/config-editor sources.\n'
        content += "'use strict';\n"
        content += "if (nexus.input.trigger === 'config-repair') {\n"
        content += (SOURCE / 'repair.js').read_text(encoding='utf-8')
        content += '\nnexus.proposeRepair(proposeRepair(nexus.input));\n} else if (nexus.input.trigger === "config-edit-commit") {\n'
        commit = SOURCE / (data['artifactName'] + '.commit.js')
        if commit.exists():
            content += commit.read_text(encoding='utf-8')
        content += '\n} else {\n'
        if preparation.exists():
            content += preparation.read_text(encoding='utf-8')
        content += '\n}\n'
        target = manifest.parent / 'data/editor.js'
        if data.get('configEditor') != 'data/editor.js':
            raise ValueError('Editor must be declared: ' + data['artifactName'])
        if check:
            if not target.exists() or target.read_text(encoding='utf-8') != content:
                failures.append(data['artifactName'])
        else:
            target.write_text(content, encoding='utf-8', newline='\n')
        count += 1
    if failures:
        raise ValueError('Generated editors differ: ' + ', '.join(failures))
    print(('Checked' if check else 'Generated') + f' {count} configuration editors')


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    generate(parser.parse_args().check)
