"""Deterministically bundle reviewed task adapters; --check never modifies sources."""
from __future__ import annotations
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / 'tools' / 'task-protocol'

def generate(check: bool) -> None:
    metadata = json.loads((SOURCE / 'adapters.json').read_text(encoding='utf-8'))
    common = (SOURCE / 'common.js').read_text(encoding='utf-8')
    failures = []
    for artifact, adapter in metadata.items():
        implementation = (SOURCE / (adapter['implementation'] + '.js')).read_text(encoding='utf-8')
        content = '// Generated by tools/generate_task_protocol.py. Edit tools/task-protocol sources.\n'
        content += 'const ADAPTER = ' + json.dumps(adapter, ensure_ascii=False, separators=(',', ':')) + ';\n'
        content += common + '\n' + implementation + '\nconsole.log(dispatch());\n'
        for name in ('discover.js', 'judge.js', 'retry.js'):
            path = ROOT / 'plugins' / 'specialized' / artifact / 'data' / name
            if check:
                if not path.exists() or path.read_text(encoding='utf-8') != content: failures.append(str(path.relative_to(ROOT)))
            else: path.write_text(content, encoding='utf-8', newline='\n')
    if failures: raise SystemExit('Generated task adapters differ: ' + ', '.join(failures))
    print(('Checked' if check else 'Generated') + ' 18 backend scripts for 6 task adapters')

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    generate(parser.parse_args().check)
